### ISSUE TITLE
Possible memory lake

### ISSUE THREAD

**Issue by pishguy** [lopspower/CircularFillableLoaders#13]
i get error when i using this useful library on my application

`executing CustomActivityOnCrash's UncaughtExceptionHandler  java.lang.OutOfMemoryError: Failed to allocate a 8271388 byte allocation with 6780384 free bytes and 6MB until OOM`

FULL error stack

```
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
at com.mikhaellopez.circularfillableloaders.CircularFillableLoaders.updateWaveShader(CircularFillableLoaders.java:210)
at com.mikhaellopez.circularfillableloaders.CircularFillableLoaders.updateShader(CircularFillableLoaders.java:201)
at com.mikhaellopez.circularfillableloaders.CircularFillableLoaders.loadBitmap(CircularFillableLoaders.java:169)
at com.mikhaellopez.circularfillableloaders.CircularFillableLoaders.onDraw(CircularFillableLoaders.java:112)
```

**Comment by lopspower** [comment]
It's really strange. Have you had this problem again?

**Comment by pishguy** [comment]
Yes @lopspower  I still have this problem

**Comment by lopspower** [comment]
Do you have additional information? On which device and Android version?
The problem is it not the size of your image (src)?

**Comment by pishguy** [comment]
@lopspower  yes sure, my tested android was 6.0.1.
i have empty bitmap on background of that as transparent

**Comment by fxo140130** [comment]
I have the same issue too. Memory leak
